export const Alumnis = [
  {
    batch: {
      id: 'b_2018',
      title: 'Alumni 2K18',
      heading: 'IETE 2K18',
      peoples: [
        {
          id: 1,
          photo: '/img/alumni/Abhishek Pandey.jpg',
          name: 'Abhishek Pandey',
          brand: '/img/alumni/samsung.png',
          linkedIn_link: 'https://www.linkedin.com/in/abhishekpandey921/',
          designation: 'Chairperson',
          company_name: 'Samsung',
        },
        {
          id: 2,
          photo: '/img/alumni/abhijit.jpg',
          name: 'Abhijit Parshar',
          brand: '/img/alumni/Vedanta.png',
          linkedIn_link:
            'https://www.linkedin.com/in/abhijit-parashar-811b34112/',
          designation: 'Vice Chairperson',
          company_name: 'Vedanta',
        },
        {
          id: 3,
          photo: '/img/alumni/Nidhi.jpg',
          name: 'Nidhi Kumari',
          brand: '/img/alumni/Deloitte.png',
          linkedIn_link:
            'https://www.linkedin.com/in/abhijit-parashar-811b34112/',
          designation: 'Vice Chairperson',
          company_name: 'Deloitte',
        },
        {
          id: 4,
          photo: '/img/alumni/Rumman.jpg',
          name: 'Rumman Akhtar',
          brand: '/img/alumni/cogni.png',
          linkedIn_link: 'https://www.linkedin.com/in/rummanakhtar/',
          designation: 'General Secretary & Alumni Incharge',
          company_name: 'Cognizant',
        },
        {
          id: 5,
          photo: '/img/alumni/kiran.jpg',
          name: 'Kiran Kumari',
          brand: '/img/alumni/Deloitte.png',
          linkedIn_link: 'https://www.linkedin.com/in/kiran-kumari-k99/',
          designation: 'Technical Secretary',
          company_name: 'Deloitte',
        },
        {
          id: 6,
          photo: '/img/alumni/Roshan.jpg',
          name: 'Roshan Kr. Singh',
          brand: '/img/alumni/samsung.png',
          linkedIn_link: 'https://www.linkedin.com/in/roshan-kumar-singh/',
          designation: 'Treasurer',
          company_name: 'Samsung',
        },
        {
          id: 7,
          photo: '/img/alumni/Pallavi.jpg',
          name: ' Pallavi Singh',
          brand: '/img/alumni/schlumberger.png',
          linkedIn_link: 'https://www.linkedin.com/in/priyapp//',
          designation: 'Joint Treasurer & Media Head',
          company_name: 'Schlumberger',
        },
        {
          id: 8,
          photo: '/img/alumni/shailesh.jpg',
          name: ' Shailesh Aanand',
          brand: '/img/alumni/google.png',
          linkedIn_link: 'https://www.linkedin.com/in/shailesh-aanand/',
          designation: 'Technical Head',
          company_name: 'Google',
        },
        {
          id: 9,
          photo: '/img/alumni/Deepak.jpg',
          name: ' Deepak Kumar',
          brand: '/img/alumni/Deloitte.png',
          linkedIn_link: 'https://www.linkedin.com/in/deepak7870',
          designation: 'Event Management Head & PRO',
          company_name: 'Deloitte',
        },
        {
          id: 10,
          photo: '/img/alumni/Suraj.jpeg',
          name: ' Suraj Kumar Mahato',
          brand: '/img/alumni/NPCI.png',
          linkedIn_link: 'https://www.linkedin.com/in/suraj-sloth/',
          designation: 'Head of Operations & Workshop Incharge',
          company_name: 'NPCI',
        },
        {
          id: 11,
          photo: '/img/alumni/anjali.jpg',
          name: ' Anjali singh',
          brand: '/img/alumni/pi_industries.png',
          linkedIn_link: 'https://www.linkedin.com/in/anjali-singh-506502215/',
          designation: 'Alumni Incharge & PRO',
          company_name: 'PI Industry',
        },
        {
          id: 11,
          photo: '/img/alumni/Subhabrata.jpg',
          name: ' Subhabrata Roy',
          brand: '/img/L&T.png',
          linkedIn_link: 'https://www.linkedin.com/in/subhabrata-roy-84038b180',
          designation: 'Media & Marketing Head',
          company_name: 'LnT',
        },
      ],
    },
  },

  {
    batch: {
      id: 'b_2017',
      title: 'Alumni 2K17',
      heading: 'IETE 2K17',
      peoples: [
        {
          id: 1,
          photo: '/img/alumni/Abhishek Pandey.jpg',
          name: 'Abhishek Pandey',
          brand: '/img/alumni/samsung.png',
          linkedIn_link: 'https://www.linkedin.com/in/abhishekpandey921/',
          designation: 'Chairperson',
          company_name: 'Samsung',
        },
        {
          id: 2,
          photo: '/img/alumni/abhijit.jpg',
          name: 'Abhijit Parshar',
          brand: '/img/alumni/Vedanta.png',
          linkedIn_link:
            'https://www.linkedin.com/in/abhijit-parashar-811b34112/',
          designation: 'Vice Chairperson',
          company_name: 'Vedanta',
        },
      ],
    },
  },
  {
    batch: {
      id: 'b_2016',
      title: 'Alumni 2K16',
      heading: 'IETE 2K16',
      peoples: [
        {
          id: 1,
          photo: '/img/alumni/Abhishek Pandey.jpg',
          name: 'Abhishek Pandey',
          brand: '/img/alumni/samsung.png',
          linkedIn_link: 'https://www.linkedin.com/in/abhishekpandey921/',
          designation: 'Chairperson',
          company_name: 'Samsung',
        },
        {
          id: 2,
          photo: '/img/alumni/abhijit.jpg',
          name: 'Abhijit Parshar',
          brand: '/img/alumni/Vedanta.png',
          linkedIn_link:
            'https://www.linkedin.com/in/abhijit-parashar-811b34112/',
          designation: 'Vice Chairperson',
          company_name: 'Vedanta',
        },
      ],
    },
  },
];
